<?php
/* autogenerated file by admin/class/config.php */

define('SITE_NAME', 'BLANK-SITE');/*the site name*/
define('ENABLE_CACHING', '0');/*enable sql query cashing: yes = 1, no = 0*/
define('SHOW_DEBUG', '1');/*show debug: yes = 1, no = 0*/
define('SITE_IS_DOWN', '0');/*site offline: yes = 1, no = 0*/
define('META_LOGO_IMAGE', 'http://www.blank-site.com/images/default/logo.png');/*the creator of the site*/
define('META_CREATOR', 'BLANK-SITE');/*the creator of the site*/
define('META_TITLE', 'Blank Site');/*the basic title of the site*/
define('META_DESCRIPTION', 'BLANK-SITE');/*the basic description of the site*/
define('META_KEYWORDS', 'BLANK-SITE');/*the basic keyword of the site*/
define('META_COPYRIGHT', 'dwizzel');/*the basic copyright*/
define('META_URL_IDENTIFIER', 'http://www.blank-site.com/');/*the basic copyright*/
define('META_DATE', '2020');/*meta date*/
define('LANG_ENABLED', 'fr_CA,en_US,es_MX');/*all languages enabled comma seperated*/
define('LANG_DEFAULT', 'en_US');/*the lang by default*/
define('EMAIL_ORIGINE_COURRIEL', '');/*the address from witch email are sent*/
define('EMAIL_ORIGINE_NOM', 'BLANK-SITE');/*the name showing in the email*/
define('REMOTE_ADDR_ACCEPTED', '127.0.0.1');/*remote address that can access the site when it's offline*/

//END