<?php
/**
@auth:	Dwizzel
@date:	00-00-0000
@info:	essentials web site defined, used all across the site, there is aan include at the bottom so user can overwrite those with is own
*/
	
//-----------------------------------------------------------------------------------------------

// DEFINE
define('VERSION', '1.0.0');
define('IS_DEFINED', 1);
define('EOL', "\n");
define('TAB', "\t");

//BASIC
date_default_timezone_set('America/New_York');

// DEFAULT BRANDING AND VERSIONING
define('DEFAULT_VERSIONING', '003');

//LOADABLE
define('SITE_DEFINE_EDITABLE','define-editable.php');

//this is the file generated by the admin interface to overwrite the values above
//NB: TEMPLATE_ANEM is in this file
require_once(SITE_DEFINE_EDITABLE);

// ABSOLUTE PATH
define('DIR', 'C:/dwizzel-local-server/code/www/github.com/dwizzel-dev/jautocomplete/');

define('DIR_CLASS', DIR.'Classes/');
define('DIR_INCLUDE', DIR.'include/');
define('DIR_CACHE', DIR.'temp/cache/');

//LES FICHIER CACHE POUR SEARCH EN JS ET PHP
define('DIR_RENDER_KW_PHP', DIR_CACHE.'js/db-kw.en_US.data');
define('DIR_RENDER_MAKE_PHP', DIR_CACHE.'js/db-make.en_US.data');

// RELATIVE PATH
define('PATH_WEB', '/');/*the base web site path*/

define('SIMPLIFIED_URL', 0);
if(SIMPLIFIED_URL){
	define('PATH_HOME', PATH_WEB);	
	define('PATH_SERVICE', PATH_WEB.'service/');
	define('PATH_FORM_PROCESS', PATH_WEB.'process/');
}else{
	define('PATH_HOME', PATH_WEB.'index.php');
	define('PATH_SERVICE', PATH_WEB.'service.php');
	define('PATH_FORM_PROCESS', PATH_WEB.'process-form.php');
	}

define('PATH_CSS', PATH_WEB.'css/');
define('PATH_JS', PATH_WEB.'js/');
define('PATH_CACHE_JS', PATH_WEB.'temp/cache/js/');
define('PATH_IMAGE', PATH_WEB.'images/');

//OTHER
define('ERROR_LEVEL', E_ALL);


//THE AUTOLOADER
spl_autoload_register(function($className) {
	include_once $_SERVER['DOCUMENT_ROOT'].'/' .$className . '.php';
});




//EOF